# Generated by Django 4.1.3 on 2022-12-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxsulot',
            options={'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulot'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Message'},
        ),
    ]
