# Generated by Django 4.1.3 on 2022-12-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
